development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://gcstubwpnlsamh:0fee5d75df6fe445454ee2ef72d6771023d041a26dd7cdc5b48eca4eb46b82be@ec2-54-83-196-179.compute-1.amazonaws.com:5432/d8oqarumrqq3mg
  channel_prefix: app_production
